---
---

<link rel="stylesheet" href="style.css" type="text/css">

&nbsp;

**<span style="color:#4682b4; font-size: 13pt; font-family:'Arial'">Please find my CV below <span>**

<iframe width="1000" height="1000" src="files/cv/Joanna_Li_CV_202607_web.pdf"></iframe>

&nbsp;

**<span style="color:#4682b4; font-size: 13pt; font-family:'Arial'">Publications <span>** <span style="color:#778899; font-size: 11pt; font-family:'Arial'">(\* denotes equal first author)</span>

<p style="color:#778899; font-size: 13pt; font-family:'Arial'"> &bull; Juan Bu, Eric Zhao, Krista Li, and **Joanna Li** (2022). "Multilevel optimal distinctiveness: Examining the impact of within- and between-organization distinctiveness of product design on market performance." ***Strategic Management Journal***, 43(9), 1793-1822.</p>

<p style="color:#778899; font-size: 13pt; font-family:'Arial'"> &bull; Jianhua Ge, **Joanna Li**\*, Eric Zhao, and Fan Yang (2022). "Rags to riches? Entrepreneurs' social classes, resourceful time allocation, and venture performance." ***Journal of Business Venturing***, 37(5), 106248.</p>

<p style="color:#778899; font-size: 13pt; font-family:'Arial'"> &bull; Trent Williams, **Joanna Li**, and Eric Zhao (2025). "Entrepreneurial Resourcefulness: Theoretical Origins, Integrative Review, and Research Agenda." ***Journal of Management Studies***, 62(7), 3220-3258.</p>

&nbsp;

**<span style="color:#4682b4; font-size: 13pt; font-family:'Arial'">Working Paper <span>**

<p style="color:#778899; font-size: 13pt; font-family:'Arial'"> &bull; Curating Inequality? Platform Intermediation and Gender Gaps in Music Streaming <br>&nbsp; with Tomasz Obloj (Revise and Resubmit at *Organization Science*; available at [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5353383))</p>

&nbsp;

**<span style="color:#4682b4; font-size: 13pt; font-family:'Arial'">Book Chapter <span>**

<p style="color:#778899; font-size: 13pt; font-family:'Arial'"> &bull; David Zhu, Eric Zhao and **Joanna Li** (2023). "Empirical design and analysis using panel data." In *Empirical Methods in Organization and Management Research*, 4th Edition. Ed. Xiaoping Chen and Wei Shen. Beijing, China: Peking University Press. [in Chinese]</p>
